name: own_music_player
description: "Music player app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.2.2
  shared_preferences: ^2.3.3
  cached_network_image: ^3.4.1
  intl: ^0.20.1
  flutter_svg: ^2.0.16
  fluttertoast: ^8.2.8
  shimmer_animation: ^2.2.1
  url_launcher: ^6.3.1
  dart_des: ^1.0.2
  audio_service: ^0.18.15
  just_audio: ^0.9.42
  marquee: ^2.3.0

  audio_session: any
  rxdart: ^0.28.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/flags/
    - assets/font/
    - assets/images/
    - assets/language/
    - assets/svgs/

  fonts:
    - family: 'regular'
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
    - family: 'medium'
      fonts:
        - asset: assets/font/Roboto-Medium.ttf
    - family: 'bold'
      fonts:
        - asset: assets/font/Roboto-Bold.ttf



